
TaskName: "veturbo-llm-13b"
# description for this task
Description: "veturbo-llm-13b"
# entry point command
Entrypoint: "cd /root/code && bash run_pretrain.sh"
# Args: ""
Tags: []
# user code path
UserCodePath: ./
# remote path mount in container
RemoteMountCodePath: "/root/code/"
ImageUrl: "vemlp-cn-beijing.cr.volces.com/preset-images/pytorch:2.0.0"

ResourceQueueID: "替换为您自己的队列ID"

# DL framework, support: TensorFlow PS,PyTorch DDP,Horovod,BytePS
Framework: "PyTorchDDP"
# Flavor代表机型，去 https://www.volcengine.com/docs/6459/72363 查询
TaskRoleSpecs:
    - RoleName: "worker"
      RoleReplicas: 4
      Flavor: "ml.hpcpni2.28xlarge"

ActiveDeadlineSeconds: 432000
EnableTensorBoard: false

Envs:
  - Name: "MLP_TRACKING_ENABLE"
    Value: "false"



# 挂载 vePFS 文件系统
Storages:
  - Type: "Vepfs"
    MountPath: "/vepfs/"
    Prefix: "/vepfs/"

AccessType: "Queue"